SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - textagroup\brafton_api\Extensions\BraftonSiteConfigExtension
# SilverStripe\SiteConfig\SiteConfig:
#   extensions:
#     - textagroup\brafton_api\Extensions\BraftonFactoryExtension
